
all:
	make -C gem
	make -C dvx
	make -C win
	make -C os2
	make -C mgw

clean:

distclean:
	rm -f *~
	rm -f gem/*~
	rm -f dvx/*~
	rm -f win/*~
	rm -f mgw/*~
	rm -f os2/*~
	rm -f ../include/*~
	rm -f ../include/mfs/*~
	rm -f ../include/gem/*~
	rm -f ../include/dvx/*~
	rm -f ../include/win/*~
	rm -f ../include/mgw/*~
	rm -f ../include/os2/*~

.PHONY: all clean distclean

