
# Template for all targets

ifndef USING
USING=$(PLATFORM)
endif

SRCDIR=..
BINDIR=../../../bin
OBJDIR=../../../obj
INCDIR=../../include
SRCFILES+=$(SRCDIR)/common.c $(SRCDIR)/$(USING)/pfspec.c
ifndef GCC
SRCFILES+= $(SRCDIR)/libc.c
endif
HDRFILES+=$(INCDIR)/api.h $(INCDIR)/libc.h $(INCDIR)/types.h $(INCDIR)/internal.h

ifdef GCC
include ../Makefile.gnu
else
include ../Makefile.watcom
endif

