
# Makefile for Windows 1.x-3.x (16-bit, large model)

export PATH:=$(WATCOM)/binl:$(PATH)
export INCLUDE:=$(WATCOM)/h:$(WATCOM)/h/win

PLATFORM=win
LIBSUFFIX=1l
WCL=wcl
CFLAGS=-bt=windows -zW -zdf -dWINDOWS_TARGET_VERSION=1 -ml

include ../Makefile.template

