
all: $(BINDIR)/$(PLATFORM)/001$(VERSION)$(EXESFX)

$(OBJDIR)/001/$(PLATFORM)/%$(VERSION)$(OBJSFX): %.c
	mkdir -p `dirname $@`
	$(CC) $(CFLAGS) $< -c $(CCOUT)$@ $(CCDEF)GUI_`echo $(PLATFORM) | tr [:lower:] [:upper:]`

$(BINDIR)/$(PLATFORM)/001$(VERSION)$(LNKSFX): $(OBJDIR)/001/$(PLATFORM)/main$(VERSION)$(OBJSFX) $(LIBS)
	mkdir -p `dirname $@`
	$(LD) $< $(LDOUT) $@ $(LDFLAGS)

