
all: $(BINDIR)/$(PLATFORM)/002$(VERSION)$(EXESFX)

$(OBJDIR)/002/$(PLATFORM)/%$(VERSION)$(OBJSFX): %.c
	mkdir -p `dirname $@`
	$(CC) $(CFLAGS) $< -c $(CCOUT)$@ $(CCDEF)GUI_`echo $(PLATFORM) | tr [:lower:] [:upper:]`

$(BINDIR)/$(PLATFORM)/002$(VERSION)$(LNKSFX): $(OBJDIR)/002/$(PLATFORM)/main$(VERSION)$(OBJSFX) $(LIBS)
	mkdir -p `dirname $@`
	$(LD) $< $(LDOUT) $@ $(LDFLAGS)
	$(postprocess)

