
# Makefile for OS/2 (16-bit, small model)

export PATH:=$(WATCOM)/binl:$(PATH)
export INCLUDE:=$(WATCOM)/h:$(WATCOM)/h/os21x

PLATFORM=os2
LIBSUFFIX=-s
WCL=wcl
CFLAGS=-bt=os2_pm -s -ms

include ../Makefile.template

