
all: $(BINDIR)/$(PLATFORM)/004$(VERSION)$(EXESFX)

$(OBJDIR)/004/$(PLATFORM)/%$(VERSION)$(OBJSFX): %.c
	mkdir -p `dirname $@`
	$(CC) $(CFLAGS) $< -c $(CCOUT)$@ $(CCDEF)GUI_`echo $(PLATFORM) | tr [:lower:] [:upper:]`

$(BINDIR)/$(PLATFORM)/004$(VERSION)$(LNKSFX): $(OBJDIR)/004/$(PLATFORM)/main$(VERSION)$(OBJSFX) $(LIBS)
	mkdir -p `dirname $@`
	$(LD) $< $(LDOUT) $@ $(LDFLAGS)

