
all:
	make -f mfs/Makefile.gem-s
	make -f mfs/Makefile.gem-l
	make -f mfs/Makefile.dvx-s
	make -f mfs/Makefile.dvx-l
	make -f mfs/Makefile.win1x-s
	make -f mfs/Makefile.win1x-l
	make -f mfs/Makefile.win3x-s
	make -f mfs/Makefile.win3x-l
	make -f mfs/Makefile.win32
	make -f mfs/Makefile.win386
	make -f mfs/Makefile.os2-s
	make -f mfs/Makefile.os2-l
	make -f mfs/Makefile.os2v2

clean:

distclean:
	rm -f *~

.PHONY: all clean distclean

