
#### Makefile for DESQview/X (16-bit, large model)

BINDIR=../../../bin
OBJDIR=../../../obj
INCDIR=../../include

export PATH:=$(WATCOM)/binl:$(PATH)
export INCLUDE:=$(WATCOM)/h

VERSION=-l
PLATFORM=dvx
EXESFX=.exe
LNKSFX=$(EXESFX)
WCL=wcl
CFLAGS=-bt=dos -i=$(INCDIR) -i=$(INCDIR)/$(PLATFORM) -ml
LDFLAGS=system dos libpath $(BINDIR)/lib/$(PLATFORM) lib xcblibl lib dtk-l
LIBS=$(BINDIR)/lib/$(PLATFORM)/dtk-l.lib

include Makefile.main

